export default {
    APP_BACKGROUND_COLOR: "#D1D3D466",
    WHITE_COLOR : "#FFFFFF",
    BLACK_COLOR:'#000000',
    BOTTOM_BORDER_COLOR: "#E0E6F3",
    GREEN_BORDER_COLOR:"#8ED9D1",
    BACKGROUND_GREEN_COLOR:"#F1FAFA",
    GREEN_TEXT_COLOR:'#1B4633',
    GREEN_PRIMARY_COLOR:'#8ED9D1',
    GRAY_TEXT_COLOR:'#9DA8C3',
    PIE_CHART_RED_COLOR:'#EB5042',
    PIE_CHART_ORANGE_COLOR:'#FFCF81',
    PIE_CHART_LIGHT_GREEN_COLOR : '#94D3A6',
    PIE_CHART_PINK_COLOR:'#E1C8E1',
    PIE_CHART_GRAY_COLOR:'#E9ECF1',
    LIGHT_BLACK_TEXT_COLOR:'#1C1B1F',
    EXTRA_LIGHT_GRAY_COLOR:'#676767',

    SLEEP_BACKGROUND_COLOR:'#A4B4CB',
    HEART_RATE_BACKGROUND_COLOR:'#FFBAB3',
    HEART_RATE_SELECTOR_COLOR : '',
    TEMPARATURE_BACKGROUND_COLOR:'#FFDEA6',
    SPORT_RECORD_BACKGROUND_COLOR:'#94D3A6',
    BODY_WEIGHT_BACKGROUND_COLOR:'#E2F6F4',
    DISTANCE_BACKGROUND_COLOR:'#FFCF81',
    BODY_PRESSURE_BACKGROUND_COLOR:'#E1C8E1',

    TAB_BAR_TEXT_GRAY_COLOR:'#A4A8B5',
    TIME_TEXT_GRAY_COLOR:'#848A9C',
    SEPARATOR_COLOR:'#E1E3E8',

    FALLASLEEP_SELECTOR_COLOR : '#cbf5d777',
    LIGHT_SLEEP_SELECTOR_COLOR : '#F4E1F555',
    DEEP_SLEEP_SELECTER_COLOR : '#D4F3F299',
    AWAKE_SELECTOR_COLOR : '#FFF1D999'

  };